version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./:/var/www/testMariadbShop
    depends_on:
      - db
      - app
  app:
    build: 
        context: .
        dockerfile: docker/Fpm.Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/testMariadbShop
    links:
      - db
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testMariadbShop
      MYSQL_ROOT_PASSWORD: password

volumes:
  db: